### generate users
GET http://localhost:3000/api/users/generate
Accept: application/json


### Add user
POST  http://localhost:3000/api/admin/add-user
Authorization: Bearer 
Content-Type: application/json

{
    "email":"sujan@gmail.com",
    "password":"password",
    "name":"Sujan Lama",
    "role":"Admin"
}

### delete user
DELETE http://localhost:3000/api/admin/delete-user/a@a.com 


### login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"password"
}

### check email address unique
GET http://localhost:3000/api/users/verify/sujan2@gmail.com


### get users
GET http://localhost:3000/api/admin/users
Authorization: Bearer 