const mongoose = require("mongoose")

const Schema = mongoose.Schema;

const schema = new Schema({
     // _id: String, -> removed for convenience - Id will be generated by mongodb
     // Its not going to affect the login/signup code as id is not used anywhere
    email: String,
    password: String,
    name:String,
    role:String
});

module.exports = {"Users": mongoose.model("Users", schema), "UserSchema" : schema};